M48
; DRILL file {KiCad 8.0.5} date 2024-10-16T11:49:29+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-16T11:49:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.028Y-2.1606
X4.2555Y-2.1606
T2
X4.5669Y-2.0773
X4.8819Y-2.0773
M30
