M48
; DRILL file {KiCad 9.0.0} date 2025-03-08T15:48:48+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-08T15:48:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X3.8429Y-2.0344
X4.0705Y-2.0344
T2
X4.7815Y-1.939
X5.0965Y-1.939
M30
